name: Set Azure Resource Manager environment variables
description: Sets the environment variables suitable for running Terraform.

inputs:
  azure-credentials:
    description: A JSON string containing service principle credentials.
    required: true

runs:
  using: composite
  steps:
    - name: Extract and set environment variables
      shell: pwsh
      run: |
        $AZURE_CREDENTIALS_JSON = '${{ inputs.azure-credentials }}'

        $ARM_CLIENT_ID = ( $AZURE_CREDENTIALS_JSON | ConvertFrom-Json ).clientId
        Write-Output "::add-mask::$ARM_CLIENT_ID"
        "ARM_CLIENT_ID=$ARM_CLIENT_ID" >> $env:GITHUB_ENV

        $ARM_CLIENT_SECRET =  ( $AZURE_CREDENTIALS_JSON | ConvertFrom-Json ).clientSecret
        Write-Output "::add-mask::$ARM_CLIENT_SECRET"
        "ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" >> $env:GITHUB_ENV

        $ARM_SUBSCRIPTION_ID =  ( $AZURE_CREDENTIALS_JSON | ConvertFrom-Json ).subscriptionId
        Write-Output "::add-mask::$ARM_SUBSCRIPTION_ID"
        "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" >> $env:GITHUB_ENV

        $ARM_TENANT_ID =  ( $AZURE_CREDENTIALS_JSON | ConvertFrom-Json ).tenantId
        Write-Output "::add-mask::$ARM_TENANT_ID"
        "ARM_TENANT_ID=$ARM_TENANT_ID" >> $env:GITHUB_ENV
