version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (repo and reusable workflows): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/AddTrelloComment"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (AddTrelloComment): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/CheckServicePrincipal"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (CheckServicePrincipal): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/CopyPRtoRelease"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (CopyPRtoRelease): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/DraftReleaseByTag"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (DraftReleaseByTag): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/GenerateReleaseFromSHA"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (GenerateReleaseFromSHA): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/SendToLogit"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (SendToLogit): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/backup-postgres"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (backup-postgres): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/build-docker-image"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (build-docker-image): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/delete-review-app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (delete-review-app): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/deploy-domains-env"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (deploy-domains-env): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/deploy-domains-infra"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (deploy-domains-infra): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/deploy-to-aks"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (deploy-to-aks): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/fix-airbyte-lsn"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (fix-airbyte-lsn): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/fix-airbyte-replication-slot"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (fix-airbyte-replication-slot): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/install-postgres-client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (install-postgres-client): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/maintenance"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (maintenance): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/monitor-postgres-wal"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (monitor-postgres-wal): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/ptr-postgres"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (ptr-postgres): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/restore-deleted-postgres"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (restore-deleted-postgres): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/restore-postgres-backup"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (restore-postgres-backup): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/review-app-reconcile"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (review-app-reconcile): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/sast-reusable-workflow"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (sast-reusable-workflow): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/send-to-teams-channel"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (send-to-teams-channel): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/set-arm-environment-variables"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (set-arm-environment-variables): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/set-kubectl"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (set-kubectl): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/set-kubelogin-environment"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (set-kubelogin-environment): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/set-up-environment"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (set-up-environment): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/sonarscan-dotnet"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (sonarscan-dotnet): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/validate-infra"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (validate-infra): "
    labels:
      - "DevOps"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/validate-key-vault-secrets"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot (validate-key-vault-secrets): "
    labels:
      - "DevOps"
      - "dependencies"

