version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (repo and reusable workflows): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/AddTrelloComment"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (AddTrelloComment): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/backup-postgres"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (backup-postgres): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/build-docker-image"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (build-docker-image): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/CheckServicePrincipal"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (CheckServicePrincipal): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/CopyPRtoRelease"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (CopyPRtoRelease): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
          
  - package-ecosystem: "github-actions"
    directory: "/DraftReleaseByTag"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (DraftReleaseByTag): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/GenerateReleaseFromSHA"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (GenerateReleaseFromSHA): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/install-postgres-client"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (install-postgres-client): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/ptr-postgres"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (ptr-postgres): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
          
  - package-ecosystem: "github-actions"
    directory: "/restore-postgres-backup"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (restore-postgres-backup): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/SendToLogit"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (SendToLogit): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/set-arm-environment-variables"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (set-arm-environment-variables): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/set-kubectl"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (set-kubectl): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
          
  - package-ecosystem: "github-actions"
    directory: "/set-kubelogin-environment"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (set-kubelogin-environment): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/set-up-environment"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (set-up-environment): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/validate-key-vault-secrets"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (validate-key-vault-secrets): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
