name: Install Postgres client
description: Install Postgres client
inputs:
  version:
    description: Postgres version
    required: true
    default: '11'
runs:
  using: composite
  steps:
  - name: Install Postgres client
    shell: bash
    id: install_postgres_client
    run: |
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      RELEASE=$(lsb_release -cs)
      echo "deb http://apt.postgresql.org/pub/repos/apt/ ${RELEASE}"-pgdg main | sudo tee  /etc/apt/sources.list.d/pgdg.list
      cat /etc/apt/sources.list.d/pgdg.list
      sudo apt-get update
      sudo apt-get install -y postgresql-client-"${{inputs.version}}"
      psql --version
