name: Build docker image
description: Build a docker image and push it to Github container registry

inputs:
  docker-repository:
    description: Repository name in the container registry. e.g. ghcr.io/dfe-digital/register-trainee-teachers. Defaults to current Github repository name.
    default: ghcr.io/${{ github.repository }}
  github-token:
    description: Default Github token retrieved via secrets.GITHUB_TOKEN or PAT with permission to the repository (Required)
    required: true
  snyk-token:
    description: Snyk token for image vulnerability scanning (Default = none)
  reuse-cache:
    description: Use previously built docker image layers to improve build time. Set to false to refresh image (Default = true)
    default: true
  dockerfile-path:
    description: Relative path to the Dockerfile (Default = ./Dockerfile)
    default: ./Dockerfile
  context:
    description: Path used as file context for Docker (Default is '.')
    default: .
  target:
    description: The target stage to build of a multi-stage build
  max-cache:
    description: Use max caching for build
    default: false
    required: false
  extra-cache-repo:
    description: Use cache from separate repo
    default: ''
    required: false
  slack-webhook:
    required: false
  main-branch:
    required: false
    default: "main"
  docker-sha:
    required: false

outputs:
  tag:
    description: Docker image unique tag
    value: ${{ steps.set-outputs.outputs.tag }}
  image:
    description: Reference to the built image name with the tag suitable for Kubernetes
    value: ${{ steps.set-outputs.outputs.repo }}:${{ steps.set-outputs.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Ensure docker repository is lowercase
      shell: pwsh
      run: |
        $DockerRepository = "${{ inputs.docker-repository }}".ToLower()
        "DOCKER_REPOSITORY=$DockerRepository" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Set environment variables (push)
      if: github.event_name == 'push'
      shell: bash
      run: |
        GIT_BRANCH=${GITHUB_REF##*/}
        echo "BRANCH_TAG=$GIT_BRANCH" >> $GITHUB_ENV # GIT_BRANCH will be main for refs/heads/main
        echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: Set environment variables (pull_request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        GIT_BRANCH=${GITHUB_HEAD_REF##*/}
        echo "BRANCH_TAG=$GIT_BRANCH" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

    - name: Set environment variables (default event)
      if: github.event_name != 'push' && github.event_name != 'pull_request'
      shell: bash
      run: |
        GIT_BRANCH=$(git branch --show-current)
        BRANCH_TAG=${GIT_BRANCH##*/}
        GIT_COMMIT=$(git rev-parse HEAD)
        echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV
        echo "IMAGE_TAG=$GIT_COMMIT" >> $GITHUB_ENV

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
        echo "repo=${DOCKER_REPOSITORY}" >> "$GITHUB_OUTPUT"

    - name: Set vars
      id: set-vars
      shell: bash
      run: |
        if [[ -z "${{inputs.docker-sha }}" ]]; then
          echo DOCKER_SHA=${{ env.IMAGE_TAG }} >> "$GITHUB_ENV"
        else
          echo DOCKER_SHA=${{ inputs.docker-sha }} >> "$GITHUB_ENV"
        fi
        if [[ -z "${{ env.TAGS_VAR }}" ]]; then
          {
            echo 'TAGS_VAR<<EOF'
            echo ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
            echo ${{ env.DOCKER_REPOSITORY }}:${{ env.BRANCH_TAG }}
            echo EOF
          } >> "$GITHUB_ENV"
        fi
        if [[ -z "${{ env.MIN_CACHE_FROM_VAR }}" ]]; then
          {
            echo 'MIN_CACHE_FROM_VAR<<EOF'
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ inputs.main-branch }}
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ env.BRANCH_TAG }}
            echo EOF
          } >> "$GITHUB_ENV"
        fi
        if [[ -z "${{ env.MAX_CACHE_TO_VAR }}" ]]; then
          {
            echo 'MAX_CACHE_TO_VAR<<EOF'
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}-buildcache,mode=max
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ env.BRANCH_TAG }}-buildcache,mode=max
            echo EOF
          } >> "$GITHUB_ENV"
        fi
        if [[ -z "${{ env.MAX_CACHE_FROM_VAR }}" ]]; then
          {
            echo 'MAX_CACHE_FROM_VAR<<EOF'
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ inputs.main-branch }}-buildcache
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}-buildcache
            echo type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ env.BRANCH_TAG }}-buildcache
            echo EOF
          } >> "$GITHUB_ENV"
        fi
        if [[ -n "${{ inputs.extra-cache-repo }}" ]]; then
          {
          echo 'EXTRA_CACHE_FROM_VAR<<EOF'
          echo type=registry,ref=${{ inputs.extra-cache-repo }}:${{ inputs.main-branch }}
          echo type=registry,ref=${{ inputs.extra-cache-repo }}:${{ env.IMAGE_TAG }}
          echo type=registry,ref=${{ inputs.extra-cache-repo }}:${{ env.BRANCH_TAG }}
          echo EOF
          } >> "$GITHUB_ENV"
        fi

    - name: Build docker image using inline cache
      uses: docker/build-push-action@v6
      if: ${{ ( inputs.reuse-cache == 'true' && inputs.max-cache == 'false' ) }}
      with:
        tags: |
          ${{ env.TAGS_VAR }}
        push: false
        load: true
        cache-to: type=inline
        cache-from: |
          ${{ env.MIN_CACHE_FROM_VAR }}
          ${{ env.EXTRA_CACHE_FROM_VAR }}
        build-args: COMMIT_SHA=${{ env.DOCKER_SHA }}
        file: ${{ inputs.dockerfile-path }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false

    - name: Build docker image without reusing inline cache
      uses: docker/build-push-action@v6
      if: ${{ ( inputs.reuse-cache == 'false' && inputs.max-cache == 'false' ) }}
      with:
        tags: |
          ${{ env.TAGS_VAR }}
        push: false
        load: true
        cache-to: type=inline
        build-args: COMMIT_SHA=${{ env.DOCKER_SHA }}
        file: ${{ inputs.dockerfile-path }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false

    - name: Set up Docker Buildx
      if: ${{ inputs.max-cache == 'true' }}
      uses: docker/setup-buildx-action@v3

    - name: Build docker image using max cache
      uses: docker/build-push-action@v6
      if: ${{ ( inputs.reuse-cache == 'true' && inputs.max-cache == 'true' ) }}
      with:
        tags: |
          ${{ env.TAGS_VAR }}
        push: false
        load: true
        cache-to: |
          ${{ env.MAX_CACHE_TO_VAR }}
        cache-from: |
          ${{ env.MAX_CACHE_FROM_VAR }}
          ${{ env.EXTRA_CACHE_FROM_VAR }}
        build-args: COMMIT_SHA=${{ env.DOCKER_SHA }}
        file: ${{ inputs.dockerfile-path }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false

    - name: Build docker image without reusing max cache
      uses: docker/build-push-action@v6
      if: ${{ ( inputs.reuse-cache == 'false' && inputs.max-cache == 'true' ) }}
      with:
        tags: |
          ${{ env.TAGS_VAR }}
        push: false
        load: true
        cache-to: |
          ${{ env.MAX_CACHE_TO_VAR }}
        build-args: COMMIT_SHA=${{ env.DOCKER_SHA }}
        file: ${{ inputs.dockerfile-path }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false

    - name: setup snyk
      uses: snyk/actions/setup@master
      if: inputs.snyk-token != ''
      id: snyk
      with:
        snyk-version: v1.1297.3

    - name: snyk scan
      if: inputs.snyk-token != ''
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: |
        snyk container test ${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_SHA }} --file=${{ inputs.dockerfile-path }} --severity-threshold=high --exclude-app-vulns

    # - name: Run Snyk to check Docker image for vulnerabilities
    #   uses: snyk/actions/docker@master
    #   if: inputs.snyk-token != ''
    #   env:
    #     SNYK_TOKEN: ${{ inputs.snyk-token }}
    #   with:
    #     image: ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
    #     args: --file=${{ inputs.dockerfile-path }} --severity-threshold=high --exclude-app-vulns

    - name: Push ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} image to registry
      shell: bash
      run: docker image push --all-tags ${{ env.DOCKER_REPOSITORY }}

    - name: Unset vars
      id: unset-vars
      shell: bash
      run: |
        # null the env vars otherwise they return to the calling workflow
        {
          echo 'TAGS_VAR<<EOF'
          echo EOF
        } >> "$GITHUB_ENV"
        {
          echo 'MIN_CACHE_FROM_VAR<<EOF'
          echo EOF
        } >> "$GITHUB_ENV"
        {
          echo 'MAX_CACHE_TO_VAR<<EOF'
          echo EOF
        } >> "$GITHUB_ENV"
        {
          echo 'MAX_CACHE_FROM_VAR<<EOF'
          echo EOF
        } >> "$GITHUB_ENV"
        {
          echo 'EXTRA_CACHE_FROM_VAR<<EOF'
          echo EOF
        } >> "$GITHUB_ENV"

    - name: Notify slack channel on job failure
      uses: rtCamp/action-slack-notify@master
      if: ${{ failure() && github.ref == 'refs/heads/main' && inputs.slack-webhook != '' }}
      with:
        SLACK_USERNAME: CI Deployment
        SLACK_COLOR: failure
        SLACK_ICON_EMOJI: ':github-logo:'
        SLACK_TITLE: 'Build failure'
        SLACK_MESSAGE: ':alert: Build failure on commit ${{env.IMAGE_TAG}} :sadparrot:'
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_FOOTER: Sent from build-docker-image
