name: Validate ADF
description: Validates the ADF files in the repository using npm package @microsoft/azure-data-factory-utilities

inputs:
  github-token:
    description: Default Github token retrieved via secrets.GITHUB_TOKEN or PAT with permission to the repository (Required)
    required: true
  azure-credentials:
    description: 'A JSON string containing service principal credentials e.g. {"client_id": "x", "client_secret": "x", "subscription_id": "x", "tenant_id": "x"}'
    required: false
    default: ''
  azure-client-id:
    description: Azure service principal or managed identity client ID when using OIDC
    required: false
    default: ''
  azure-subscription-id:
    description: Azure service principal or managed identity subscription ID when using OIDC
    required: false
    default: ''
  azure-tenant-id:
    description: Azure service principal or managed identity tenant ID when using OIDC
    required: false
    default: ''
  adf-path:
    description: Relative path to the ADF directory (Default = ./adf)
    default: ./adf
  adf-resource-id:
    description: Azure Data Factory resource ID (Required)
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v7
      
    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 26

    - name: Install ADF Utilities
      shell: bash
      run: npm install @microsoft/azure-data-factory-utilities

    - uses: azure/login@v3
      with:
        creds: ${{ inputs.azure-credentials }}
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Validate ADF files
      shell: bash
      run: npm run build validate ${{ inputs.adf-path }} ${{ inputs.adf-resource-id }}  