name: Set Up Environment
description: Using a SIMPLE YAML file this will read the contents and set environment variable
inputs:
  FILE:
    description: 'YAML file containing variables'
    required:    true
    default:     .github/common_environment.yml
runs:
  using: composite
  steps:
       - name: Set-Up-Environment 
         shell: bash
         id: env
         run: |
             FILE=${{inputs.FILE}}
             while read -r line
             do
                 VAR=$(echo ${line} | sed -e 's/:[^:\/\/]/="/g;s/$/"/g;s/ *=/=/g;s/" */"/g')
                 echo ${VAR} >> $GITHUB_ENV
             done < ${FILE}

