name: Maintenance V2
description: Enable or disable maintenance for a service with centralized templates
inputs:
  # Required inputs
  environment:
    description: Name of the app environment
    required: true
  mode:
    description: Maintenance mode to implement, either enable or disable
    required: true
  
  # Azure authentication inputs
  azure-credentials:
    description: 'JSON string containing service principal credentials'
    required: false
    default: ''
  azure-client-id:
    description: Azure client ID when using OIDC
    required: false
    default: ''
  azure-subscription-id:
    description: Azure subscription ID when using OIDC
    required: false
    default: ''
  azure-tenant-id:
    description: Azure tenant ID when using OIDC
    required: false
    default: ''
  
  # Docker configuration
  docker-repository:
    description: Name of the maint app docker repository
    required: false
  github-token:
    description: GitHub token for repository access
    required: false
  
  # Config file path (optional - will use maint-config.txt if it exists)
  config-file:
    description: Path to maintenance configuration file
    required: false
    default: 'maint-config.txt'
  
  template-ref:
    description: Branch/tag/commit of teacher-services-cloud repository to use
    required: false
    default: 'main'

runs:
  using: composite
  steps:
    - uses: azure/login@v2
      if: inputs.azure-credentials != ''
      with:
        creds: ${{ inputs.azure-credentials }}

    - uses: azure/login@v2
      if: inputs.azure-credentials == ''
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Set ARM and kubelogin environment
      uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-credentials: ${{ inputs.azure-credentials }}
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Load maintenance configuration
      if: inputs.mode == 'enable'
      id: load-config
      shell: bash
      run: |
        echo "Loading maintenance configuration..."
        
        # Set default values
        SERVICE_PRETTY="This service"
        MAINTENANCE_MESSAGE="We are currently carrying out essential maintenance. Please try again later."
        ESTIMATED_RETURN=""
        STATUS_PAGE=""
        CONTACT_EMAIL=""
        
        # Check if config file exists and load it
        if [[ -f "${{ inputs.config-file }}" ]]; then
          echo "Loading configuration from ${{ inputs.config-file }}"
          # Source the config file to load variables
          source "${{ inputs.config-file }}"
        else
          echo "No config file found at ${{ inputs.config-file }}, using defaults"
        fi
        
        # Export variables for use in later steps
        echo "service-name=${SERVICE_PRETTY}" >> $GITHUB_OUTPUT
        echo "maintenance-message=${MAINTENANCE_MESSAGE}" >> $GITHUB_OUTPUT
        echo "estimated-return=${ESTIMATED_RETURN}" >> $GITHUB_OUTPUT
        echo "status-page=${STATUS_PAGE}" >> $GITHUB_OUTPUT
        echo "contact-email=${CONTACT_EMAIL}" >> $GITHUB_OUTPUT
        
        echo "Configuration loaded:"
        echo "  Service: ${SERVICE_PRETTY}"
        echo "  Message: ${MAINTENANCE_MESSAGE}"
        echo "  Contact: ${CONTACT_EMAIL}"

    - name: Fetch and customize maintenance page templates
      if: inputs.mode == 'enable'
      shell: bash
      run: |
        echo "Fetching maintenance page templates from teacher-services-cloud..."
        echo "Current directory: $(pwd)"
        echo "GitHub workspace: ${{ github.workspace }}"
        
        # Create maintenance_page directory if it doesn't exist
        mkdir -p maintenance_page
        
        # Create temp directory for cloning
        TEMP_DIR=$(mktemp -d)
        echo "Temp directory: $TEMP_DIR"
        
        # Clone only the templates directory (sparse checkout)
        cd $TEMP_DIR
        git clone --filter=blob:none --sparse https://github.com/DFE-Digital/teacher-services-cloud.git
        cd teacher-services-cloud
        git sparse-checkout set templates/new_service/maintenance_page
        git checkout ${{ inputs.template-ref }}
        
        # Debug: Check what files we have
        echo "Files in template directory:"
        ls -la templates/new_service/maintenance_page/
        
        # Copy ONLY the necessary template files (Dockerfile, nginx.conf, html)
        # DO NOT touch existing manifests or scripts directories in the service repo
        cp templates/new_service/maintenance_page/Dockerfile ${{ github.workspace }}/maintenance_page/
        cp templates/new_service/maintenance_page/nginx.conf ${{ github.workspace }}/maintenance_page/
        
        # Remove existing html directory and copy fresh from template
        rm -rf ${{ github.workspace }}/maintenance_page/html
        cp -r templates/new_service/maintenance_page/html ${{ github.workspace }}/maintenance_page/
        
        # Copy the maintenance manifests templates (deployment and service only)
        # Only copy if they don't already exist in the service repository
        if [ ! -d "${{ github.workspace }}/maintenance_page/manifests/maintenance" ]; then
          echo "Copying maintenance manifest templates from teacher-services-cloud..."
          mkdir -p ${{ github.workspace }}/maintenance_page/manifests/maintenance
          cp -r templates/new_service/maintenance_page/manifests/maintenance/* ${{ github.workspace }}/maintenance_page/manifests/maintenance/
        else
          echo "Using existing maintenance manifests from service repository"
        fi
        
        # Check if service has the required directories
        if [ ! -d "${{ github.workspace }}/maintenance_page/manifests/staging" ] && [ ! -d "${{ github.workspace }}/maintenance_page/manifests/production" ]; then
          echo "WARNING: No environment-specific manifests found in maintenance_page/manifests/"
          echo "Please ensure your repository contains:"
          echo "  - maintenance_page/manifests/staging/ (for staging environment)"
          echo "  - maintenance_page/manifests/production/ (for production environment)"
        fi
        
        if [ ! -d "${{ github.workspace }}/maintenance_page/scripts" ]; then
          echo "WARNING: No scripts directory found in maintenance_page/"
          echo "Using template scripts as fallback..."
          cp -r templates/new_service/maintenance_page/scripts ${{ github.workspace }}/maintenance_page/
        else
          echo "Using existing service-specific scripts from maintenance_page/scripts/"
        fi
        
        # Debug: Verify files were copied
        echo "Files in maintenance_page directory:"
        ls -la ${{ github.workspace }}/maintenance_page/
        
        # Clean up temp directory
        rm -rf $TEMP_DIR
        
        echo "Templates fetched successfully"
        
        # Apply customizations
        echo "Applying service customizations..."
        cd ${{ github.workspace }}
        
        # Use environment variables from the config file to replace placeholders
        # This is safer than trying to pass complex HTML through sed
        
        # Create a temporary script to do the replacements using environment variables
        cat > replace_placeholders.sh << 'SCRIPT_END'
        #!/bin/bash
        set -e
        
        # Load the config file
        if [[ -f "$1" ]]; then
          source "$1"
        else
          # Set defaults if no config file
          SERVICE_PRETTY="This service"
          MAINTENANCE_MESSAGE="We are currently carrying out essential maintenance. Please try again later."
          ESTIMATED_RETURN=""
          STATUS_PAGE=""
          CONTACT_EMAIL=""
        fi
        
        # Read the HTML file
        HTML_FILE="$2"
        
        # Use temporary files to avoid issues with special characters
        # Export variables for perl to use
        export SERVICE_PRETTY
        export MAINTENANCE_MESSAGE
        export ESTIMATED_RETURN
        export STATUS_PAGE
        export CONTACT_EMAIL
        
        # Replace placeholders using perl with environment variables
        perl -i -pe 's/#SERVICE_PRETTY#/$ENV{SERVICE_PRETTY}/g' "$HTML_FILE"
        perl -i -pe 's/#MAINTENANCE_MESSAGE#/$ENV{MAINTENANCE_MESSAGE}/g' "$HTML_FILE"
        
        # Handle optional fields
        if [[ -n "${ESTIMATED_RETURN}" ]]; then
          perl -i -pe 's|#ESTIMATED_RETURN#|$ENV{ESTIMATED_RETURN}|g' "$HTML_FILE"
        else
          perl -i -pe 's|#ESTIMATED_RETURN#||g' "$HTML_FILE"
        fi
        
        if [[ -n "${STATUS_PAGE}" ]]; then
          perl -i -pe 's|#STATUS_PAGE#|$ENV{STATUS_PAGE}|g' "$HTML_FILE"
        else
          perl -i -pe 's|#STATUS_PAGE#||g' "$HTML_FILE"
        fi
        
        # Handle contact email
        if [[ -n "${CONTACT_EMAIL}" ]]; then
          CONTACT_HTML="<li>Email: <a class=\"govuk-link app-!-overflow-break-word govuk-footer__link\" href=\"mailto:${CONTACT_EMAIL}\">${CONTACT_EMAIL}</a></li>"
          CONTACT_HTML="${CONTACT_HTML}<li>We aim to respond within 5 working days, or one working day for more urgent queries</li>"
          export CONTACT_HTML
          perl -i -pe 's|#CONTACT_INFO#|$ENV{CONTACT_HTML}|g' "$HTML_FILE"
        else
          # Remove the entire Get help section if no email
          perl -i -pe 'BEGIN{undef $/;} s/<h2 class="govuk-heading-m">Get help<\/h2>.*?<\/ul>//smg' "$HTML_FILE"
        fi
        SCRIPT_END
        
        chmod +x replace_placeholders.sh
        ./replace_placeholders.sh "${{ inputs.config-file }}" "maintenance_page/html/index.html"
        rm replace_placeholders.sh
        
        echo "Customizations applied successfully"
        
        # Also need to replace placeholders in the manifests
        # Extract service name from docker repository (e.g., "teacher-success" from "ghcr.io/dfe-digital/teacher-success-maintenance")
        REPO_NAME=$(echo "${{ inputs.docker-repository }}" | sed 's|.*/||')
        SERVICE_NAME=$(echo "$REPO_NAME" | sed 's/-maintenance$//')
        echo "Extracted service name from docker repository: $SERVICE_NAME"
        echo "Service name for manifests: $SERVICE_NAME"
        
        # Replace placeholders in deployment template (but keep #MAINTENANCE_IMAGE_TAG# for the script to replace)
        sed -i "s/#SERVICE_NAME#/${SERVICE_NAME}/g" maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
        sed -i "s|#DOCKER_REPOSITORY#|${{ inputs.docker-repository }}|g" maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
        
        # Replace placeholders in service manifest
        sed -i "s/#SERVICE_NAME#/${SERVICE_NAME}/g" maintenance_page/manifests/maintenance/service_maintenance.yml
        
        echo "Manifest placeholders replaced"

    - name: Build and push docker image
      if: inputs.mode == 'enable'
      id: build-image
      uses: DFE-Digital/github-actions/build-docker-image@master
      with:
        github-token: ${{ inputs.github-token }}
        dockerfile-path: maintenance_page/Dockerfile
        docker-repository: ${{ inputs.docker-repository }}
        context: maintenance_page

    # Note: We don't clean up maintenance_page directory here because:
    # 1. The scripts directory is needed by the Makefile for failover.sh
    # 2. The manifests directory might be needed for checking temp URLs
    # The directory will be cleaned up when the workflow ends anyway

    - name: Enable maintenance mode
      if: inputs.mode == 'enable'
      shell: bash
      run: make ci ${{ inputs.environment }} maintenance-fail-over
      env:
        MAINTENANCE_IMAGE_TAG: ${{steps.build-image.outputs.tag}}

    - name: Disable maintenance mode
      if: inputs.mode == 'disable'
      shell: bash
      run: make ci ${{ inputs.environment }} disable-maintenance

    - name: Maintenance Summary
      if: success()
      shell: bash
      run: |
        NOW=$(TZ=Europe/London date +"%F %R")
        echo '## 🚧 Maintenance Page ${{ inputs.mode }}d!' >> $GITHUB_STEP_SUMMARY
        echo '' >> $GITHUB_STEP_SUMMARY
        echo '| Field | Value |' >> $GITHUB_STEP_SUMMARY
        echo '|-------|-------|' >> $GITHUB_STEP_SUMMARY
        echo "| **Environment** | ${{ inputs.environment }} |" >> $GITHUB_STEP_SUMMARY
        echo "| **Time** | ${NOW} (London) |" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ inputs.mode }}" == "enable" ]]; then
          echo "| **Service** | ${{ steps.load-config.outputs.service-name }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Message** | ${{ steps.load-config.outputs.maintenance-message }} |" >> $GITHUB_STEP_SUMMARY
          if [[ -n "${{ steps.load-config.outputs.estimated-return }}" ]]; then
            echo "| **Estimated Return** | (See maintenance page) |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ -n "${{ steps.load-config.outputs.status-page }}" ]]; then
            echo "| **Status Page** | (See maintenance page) |" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ -n "${{ steps.load-config.outputs.contact-email }}" ]]; then
            echo "| **Contact** | ${{ steps.load-config.outputs.contact-email }} |" >> $GITHUB_STEP_SUMMARY
          fi
          echo '' >> $GITHUB_STEP_SUMMARY
          
          # Check for temp URLs if available
          if [[ -f ./maintenance_page/manifests/${{ inputs.environment }}/ingress_temp*.yml ]]; then
            echo '### Temporary URLs' >> $GITHUB_STEP_SUMMARY
            TEMP_URLS=$(awk '/name:.*cloud/ {print "- " $2}' ./maintenance_page/manifests/${{ inputs.environment }}/ingress_temp*.yml 2>/dev/null || true)
            if [[ -n "$TEMP_URLS" ]]; then
              echo "$TEMP_URLS" >> $GITHUB_STEP_SUMMARY
            fi
          fi
        fi