name: Test Validate KeyVault Secrets

on:
  pull_request:
    branches:
      - master
    paths:
    - 'validate-key-vault-secrets/**'
  push:
    paths:
    - 'validate-key-vault-secrets/**'

jobs:
  validate-key-vault-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}        

      - name: Validate Key Vault Secrets
        uses: ./validate-key-vault-secrets
        with:
          KEY_VAULT: s121d01-shared-kv-01
          SECRETS: |
            BAT-INFRA-SECRETS-QA
            FIND-APP-SECRETS-QA
