name: Link Trello card
on:
  pull_request:
    types: [ opened , edited]

jobs:
  attach-to-trello:
    name: Link Trello card to this PR
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Add Trello Comment
        uses: DFE-Digital/github-actions/AddTrelloComment@master
        with:
          MESSAGE:      ${{ github.event.pull_request.html_url }} 
          CARD:         ${{ github.event.pull_request.body }}           
          TRELLO-KEY:   ${{ secrets.TRELLO_KEY}}
          TRELLO-TOKEN: ${{ secrets.TRELLO_TOKEN }}
